### ISSUE TITLE
smartImageCache v1.1.0 conflicts with the xmpMetadata plugin in albums when both are enabled

### ISSUE THREAD

**Issue by JesseHC** [FilippoBoscarino/smartImageCache-for-Zenphoto#6]
If xmpMetadata and smartImageCache v1.1.0 are both enabled, smartImageCache will block the “Export metadata info to XMP sidecar” option in the album Utilities menu. With smartImageCache turned off, it will show.

smartImageCache off-
![smartImageCache v1 1 0 off](https://github.com/FilippoBoscarino/smartImageCache-for-Zenphoto/assets/82089671/be66cd4f-6987-47ef-abe8-eef478e8f84a)

smartImageCache on-
![smartImageCache v1 1 0 on](https://github.com/FilippoBoscarino/smartImageCache-for-Zenphoto/assets/82089671/c150e766-2487-49fd-ae32-2e5553a83872)

Thanks!

**Comment by FilippoBoscarino** [comment]
Hi Jesse,
thanks for your indication.
To be honest, it is not so clear to me the real reason of this interaction.
It seems that there is something unpredictable in the Zp explicit priority assignment of filters.
Anyway I bypassed it and the issue has been solved in v.1.1.1 release, already online.
